services:
  app:
    build: .
    container_name: client_search
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - elasticsearch
    environment:
      RAILS_ENV: development
      ELASTICSEARCH_URL: http://elasticsearch:9200

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.18.0
    container_name: elasticsearch_8
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

volumes:
  es_data:
